services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:80"
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
    ports:
      - "8080:8080"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped